import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const RepositoryComponent = dynamic(() => import('./repository'), {
  ssr: false,
});

const Home: NextPage = () => {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RepositoryComponent />
      </main>
    </div>
  )
}

export default Home
